import 'package:supabase_flutter/supabase_flutter.dart';

class AttendanceService {
  final _supabase = Supabase.instance.client;

  // Complete data from the attendance table
  final List<Map<String, dynamic>> _attendanceData = [
    {
      'serial_no': 1,
      'registration_no': '210823104001',
      'student_name': 'AATHI BALA KUMAR B (H)',
      'total_working_days': 37,
      'days_absent': 0,
      'days_present': 37,
      'attendance_percentage': 100.00,
      'department': 'Computer Science Engineering',
      'semester': 4,
    },
    {
      'serial_no': 2,
      'registration_no': '210823104002',
      'student_name': 'ABEL C JOY',
      'total_working_days': 37,
      'days_absent': 2,
      'days_present': 35,
      'attendance_percentage': 94.59,
      'department': 'Computer Science Engineering',
      'semester': 4,
    },
    {
      'serial_no': 3,
      'registration_no': '210823104003',
      'student_name': 'ABINAYA T',
      'total_working_days': 37,
      'days_absent': 2,
      'days_present': 35,
      'attendance_percentage': 94.59,
      'department': 'Computer Science Engineering',
      'semester': 4,
    },
    {
      'serial_no': 4,
      'registration_no': '210823104004',
      'student_name': 'ABISHA JEBAMANI K',
      'total_working_days': 37,
      'days_absent': 1,
      'days_present': 36,
      'attendance_percentage': 97.30,
      'department': 'Computer Science Engineering',
      'semester': 4,
    },
    {
      'serial_no': 5,
      'registration_no': '210823104005',
      'student_name': 'ABISHEK PAULSON S',
      'total_working_days': 37,
      'days_absent': 6,
      'days_present': 31,
      'attendance_percentage': 83.78,
      'department': 'Computer Science Engineering',
      'semester': 4,
    },
    {
      'serial_no': 6,
      'registration_no': '210823104006',
      'student_name': 'ABY ROSY M',
      'total_working_days': 37,
      'days_absent': 1,
      'days_present': 36,
      'attendance_percentage': 97.30,
      'department': 'Computer Science Engineering',
      'semester': 4,
    },
    {
      'serial_no': 7,
      'registration_no': '210823104007',
      'student_name': 'AKSHAYA PRABHA M (H)',
      'total_working_days': 37,
      'days_absent': 0,
      'days_present': 37,
      'attendance_percentage': 100.00,
      'department': 'Computer Science Engineering',
      'semester': 4,
    },
    {
      'serial_no': 8,
      'registration_no': '210823104008',
      'student_name': 'ANGELIN MARY S (H)',
      'total_working_days': 37,
      'days_absent': 2,
      'days_present': 35,
      'attendance_percentage': 94.59,
      'department': 'Computer Science Engineering',
      'semester': 4,
    },
    {
      'serial_no': 9,
      'registration_no': '210823104009',
      'student_name': 'ANISHA SWEETY J',
      'total_working_days': 37,
      'days_absent': 2,
      'days_present': 35,
      'attendance_percentage': 94.59,
      'department': 'Computer Science Engineering',
      'semester': 4,
    },
    {
      'serial_no': 10,
      'registration_no': '210823104010',
      'student_name': 'ANNESHARON A S',
      'total_working_days': 37,
      'days_absent': 24,
      'days_present': 13,
      'attendance_percentage': 35.14,
      'department': 'Computer Science Engineering',
      'semester': 4,
    },
    {
      'serial_no': 11,
      'registration_no': '210823104011',
      'student_name': 'ANNIE DORAH ABEL',
      'total_working_days': 37,
      'days_absent': 7,
      'days_present': 30,
      'attendance_percentage': 81.08,
      'department': 'Computer Science Engineering',
      'semester': 4,
    },
    {
      'serial_no': 12,
      'registration_no': '210823104012',
      'student_name': 'ANTONY MELVIN T',
      'total_working_days': 37,
      'days_absent': 7,
      'days_present': 30,
      'attendance_percentage': 81.08,
      'department': 'Computer Science Engineering',
      'semester': 4,
    },
    {
      'serial_no': 13,
      'registration_no': '210823104013',
      'student_name': 'ARPUTHA STEPHIN A (H)',
      'total_working_days': 37,
      'days_absent': 0,
      'days_present': 37,
      'attendance_percentage': 100.00,
      'department': 'Computer Science Engineering',
      'semester': 4,
    },
    {
      'serial_no': 14,
      'registration_no': '210823104014',
      'student_name': 'ARTHI M',
      'total_working_days': 37,
      'days_absent': 15,
      'days_present': 22,
      'attendance_percentage': 59.46,
      'department': 'Computer Science Engineering',
      'semester': 4,
    },
    {
      'serial_no': 15,
      'registration_no': '210823104015',
      'student_name': 'ARUNACHALAM R',
      'total_working_days': 37,
      'days_absent': 15,
      'days_present': 22,
      'attendance_percentage': 59.46,
      'department': 'Computer Science Engineering',
      'semester': 4,
    },
    {
      'serial_no': 16,
      'registration_no': '210823104016',
      'student_name': 'ASBOURN JOEL I',
      'total_working_days': 37,
      'days_absent': 4,
      'days_present': 33,
      'attendance_percentage': 89.19,
      'department': 'Computer Science Engineering',
      'semester': 4,
    },
    {
      'serial_no': 17,
      'registration_no': '210823104017',
      'student_name': 'ASLIN BRIMA P H (H)',
      'total_working_days': 37,
      'days_absent': 0,
      'days_present': 37,
      'attendance_percentage': 100.00,
      'department': 'Computer Science Engineering',
      'semester': 4,
    },
    {
      'serial_no': 18,
      'registration_no': '210823104018',
      'student_name': 'ASWITHA K',
      'total_working_days': 37,
      'days_absent': 0,
      'days_present': 37,
      'attendance_percentage': 100.00,
      'department': 'Computer Science Engineering',
      'semester': 4,
    },
    {
      'serial_no': 19,
      'registration_no': '210823104019',
      'student_name': 'BABY SHALINI K',
      'total_working_days': 37,
      'days_absent': 37,
      'days_present': 0,
      'attendance_percentage': 0.00,
      'department': 'Computer Science Engineering',
      'semester': 4,
    },
    {
      'serial_no': 20,
      'registration_no': '210823104020',
      'student_name': 'BALAMURUGAN M',
      'total_working_days': 37,
      'days_absent': 0,
      'days_present': 37,
      'attendance_percentage': 100.00,
      'department': 'Computer Science Engineering',
      'semester': 4,
    },
    {
      'serial_no': 21,
      'registration_no': '210823104021',
      'student_name': 'BLESSING RAJA P (H)',
      'total_working_days': 37,
      'days_absent': 1,
      'days_present': 36,
      'attendance_percentage': 97.30,
      'department': 'Computer Science Engineering',
      'semester': 4,
    },
    {
      'serial_no': 22,
      'registration_no': '210823104022',
      'student_name': 'BOAZ K',
      'total_working_days': 37,
      'days_absent': 19,
      'days_present': 18,
      'attendance_percentage': 48.65,
      'department': 'Computer Science Engineering',
      'semester': 4,
    },
    {
      'serial_no': 23,
      'registration_no': '210823104023',
      'student_name': 'CHANDRA MOHAN C (H)',
      'total_working_days': 37,
      'days_absent': 5,
      'days_present': 32,
      'attendance_percentage': 86.49,
      'department': 'Computer Science Engineering',
      'semester': 4,
    },
    {
      'serial_no': 24,
      'registration_no': '210823104024',
      'student_name': 'CHRISTYBAI JENCY K',
      'total_working_days': 37,
      'days_absent': 1,
      'days_present': 36,
      'attendance_percentage': 97.30,
      'department': 'Computer Science Engineering',
      'semester': 4,
    },
    {
      'serial_no': 25,
      'registration_no': '210823104025',
      'student_name': 'DANIYEL K L (H)',
      'total_working_days': 37,
      'days_absent': 18,
      'days_present': 19,
      'attendance_percentage': 51.35,
      'department': 'Computer Science Engineering',
      'semester': 4,
    },
    {
      'serial_no': 26,
      'registration_no': '210823104026',
      'student_name': 'DEEPA G C',
      'total_working_days': 37,
      'days_absent': 2,
      'days_present': 35,
      'attendance_percentage': 94.59,
      'department': 'Computer Science Engineering',
      'semester': 4,
    },
    {
      'serial_no': 27,
      'registration_no': '210823104027',
      'student_name': 'DEEPAK S',
      'total_working_days': 37,
      'days_absent': 9,
      'days_present': 28,
      'attendance_percentage': 75.68,
      'department': 'Computer Science Engineering',
      'semester': 4,
    },
    {
      'serial_no': 28,
      'registration_no': '210823104028',
      'student_name': 'DHANUSH A',
      'total_working_days': 37,
      'days_absent': 9,
      'days_present': 28,
      'attendance_percentage': 75.68,
      'department': 'Computer Science Engineering',
      'semester': 4,
    },
    {
      'serial_no': 29,
      'registration_no': '210823104029',
      'student_name': 'DHARNESH S',
      'total_working_days': 37,
      'days_absent': 6,
      'days_present': 31,
      'attendance_percentage': 83.78,
      'department': 'Computer Science Engineering',
      'semester': 4,
    },
    {
      'serial_no': 30,
      'registration_no': '210823104030',
      'student_name': 'DHARSHANA R',
      'total_working_days': 37,
      'days_absent': 5,
      'days_present': 32,
      'attendance_percentage': 86.49,
      'department': 'Computer Science Engineering',
      'semester': 4,
    },
    {
      'serial_no': 31,
      'registration_no': '210823104031',
      'student_name': 'DHEEKSHA B',
      'total_working_days': 37,
      'days_absent': 3,
      'days_present': 34,
      'attendance_percentage': 91.89,
      'department': 'Computer Science Engineering',
      'semester': 4,
    },
    {
      'serial_no': 32,
      'registration_no': '210823104032',
      'student_name': 'DHIVIYESH J (H)',
      'total_working_days': 37,
      'days_absent': 2,
      'days_present': 35,
      'attendance_percentage': 94.59,
      'department': 'Computer Science Engineering',
      'semester': 4,
    },
    {
      'serial_no': 33,
      'registration_no': '210823104033',
      'student_name': 'DON SINTO SAJI',
      'total_working_days': 37,
      'days_absent': 0,
      'days_present': 37,
      'attendance_percentage': 100.00,
      'department': 'Computer Science Engineering',
      'semester': 4,
    },
    {
      'serial_no': 34,
      'registration_no': '210823104034',
      'student_name': 'EASWARAMURTHY P',
      'total_working_days': 37,
      'days_absent': 4,
      'days_present': 33,
      'attendance_percentage': 89.19,
      'department': 'Computer Science Engineering',
      'semester': 4,
    },
    {
      'serial_no': 35,
      'registration_no': '210823104035',
      'student_name': 'ELANGO B',
      'total_working_days': 37,
      'days_absent': 21,
      'days_present': 16,
      'attendance_percentage': 43.24,
      'department': 'Computer Science Engineering',
      'semester': 4,
    },
    {
      'serial_no': 36,
      'registration_no': '210823104036',
      'student_name': 'ELAVARASEN S K',
      'total_working_days': 37,
      'days_absent': 10,
      'days_present': 27,
      'attendance_percentage': 72.97,
      'department': 'Computer Science Engineering',
      'semester': 4,
    },
    {
      'serial_no': 37,
      'registration_no': '210823104037',
      'student_name': 'ENOCH M',
      'total_working_days': 37,
      'days_absent': 3,
      'days_present': 34,
      'attendance_percentage': 91.89,
      'department': 'Computer Science Engineering',
      'semester': 4,
    },
    {
      'serial_no': 38,
      'registration_no': '210823104038',
      'student_name': 'GAYATHRI K',
      'total_working_days': 37,
      'days_absent': 7,
      'days_present': 30,
      'attendance_percentage': 81.08,
      'department': 'Computer Science Engineering',
      'semester': 4,
    },
    {
      'serial_no': 39,
      'registration_no': '210823104039',
      'student_name': 'GAYATHRI Kumar',
      'total_working_days': 37,
      'days_absent': 5,
      'days_present': 32,
      'attendance_percentage': 86.49,
      'department': 'Computer Science Engineering',
      'semester': 4,
    },
    {
      'serial_no': 40,
      'registration_no': '210823104040',
      'student_name': 'GOKULAKRISHNAN S',
      'total_working_days': 37,
      'days_absent': 3,
      'days_present': 34,
      'attendance_percentage': 91.89,
      'department': 'Computer Science Engineering',
      'semester': 4,
    },
    {
      'serial_no': 41,
      'registration_no': '210823104041',
      'student_name': 'GOWTHAM A',
      'total_working_days': 37,
      'days_absent': 11,
      'days_present': 26,
      'attendance_percentage': 70.27,
      'department': 'Computer Science Engineering',
      'semester': 4,
    },
    {
      'serial_no': 42,
      'registration_no': '210823104042',
      'student_name': 'HAAKASH A',
      'total_working_days': 37,
      'days_absent': 37,
      'days_present': 0,
      'attendance_percentage': 0.00,
      'department': 'Computer Science Engineering',
      'semester': 4,
    },
    {
      'serial_no': 43,
      'registration_no': '210823104043',
      'student_name': 'HARIHARAN D',
      'total_working_days': 37,
      'days_absent': 6,
      'days_present': 31,
      'attendance_percentage': 83.78,
      'department': 'Computer Science Engineering',
      'semester': 4,
    },
    {
      'serial_no': 44,
      'registration_no': '210823104044',
      'student_name': 'HARIPRIYA V S',
      'total_working_days': 37,
      'days_absent': 6,
      'days_present': 31,
      'attendance_percentage': 83.78,
      'department': 'Computer Science Engineering',
      'semester': 4,
    },
    {
      'serial_no': 45,
      'registration_no': '210823104046',
      'student_name': 'HEMALATHA S',
      'total_working_days': 37,
      'days_absent': 27,
      'days_present': 10,
      'attendance_percentage': 27.03,
      'department': 'Computer Science Engineering',
      'semester': 4,
    },
    {
      'serial_no': 46,
      'registration_no': '210823104047',
      'student_name': 'HEMAVATHI A',
      'total_working_days': 37,
      'days_absent': 5,
      'days_present': 32,
      'attendance_percentage': 86.49,
      'department': 'Computer Science Engineering',
      'semester': 4,
    },
    {
      'serial_no': 47,
      'registration_no': '210823104048',
      'student_name': 'INDIRESH D',
      'total_working_days': 37,
      'days_absent': 3,
      'days_present': 34,
      'attendance_percentage': 91.89,
      'department': 'Computer Science Engineering',
      'semester': 4,
    },
    {
      'serial_no': 48,
      'registration_no': '210823104049',
      'student_name': 'ISAI RAMYA G',
      'total_working_days': 37,
      'days_absent': 7,
      'days_present': 30,
      'attendance_percentage': 81.08,
      'department': 'Computer Science Engineering',
      'semester': 4,
    },
    {
      'serial_no': 49,
      'registration_no': '210823104050',
      'student_name': 'JACOB ADISH MOSES A',
      'total_working_days': 37,
      'days_absent': 37,
      'days_present': 0,
      'attendance_percentage': 0.00,
      'department': 'Computer Science Engineering',
      'semester': 4,
    },
    {
      'serial_no': 50,
      'registration_no': '210823104051',
      'student_name': 'JAFFI JOANNA F (H)',
      'total_working_days': 37,
      'days_absent': 4,
      'days_present': 33,
      'attendance_percentage': 89.19,
      'department': 'Computer Science Engineering',
      'semester': 4,
    },
    {
      'serial_no': 51,
      'registration_no': '210823104052',
      'student_name': 'JAKIN K',
      'total_working_days': 37,
      'days_absent': 18,
      'days_present': 19,
      'attendance_percentage': 51.35,
      'department': 'Computer Science Engineering',
      'semester': 4,
    },
    {
      'serial_no': 52,
      'registration_no': '210823104053',
      'student_name': 'JAYACHITRA B',
      'total_working_days': 37,
      'days_absent': 7,
      'days_present': 30,
      'attendance_percentage': 81.08,
      'department': 'Computer Science Engineering',
      'semester': 4,
    },
    {
      'serial_no': 53,
      'registration_no': '210823104054',
      'student_name': 'JEBARSON P (H)',
      'total_working_days': 37,
      'days_absent': 0,
      'days_present': 37,
      'attendance_percentage': 100.00,
      'department': 'Computer Science Engineering',
      'semester': 4,
    },
    {
      'serial_no': 54,
      'registration_no': '210823104055',
      'student_name': 'JEBIN JEBARAJ D',
      'total_working_days': 37,
      'days_absent': 16,
      'days_present': 21,
      'attendance_percentage': 56.76,
      'department': 'Computer Science Engineering',
      'semester': 4,
    },
    {
      'serial_no': 55,
      'registration_no': '210823104057',
      'student_name': 'JENIFER POOMANI J (H)',
      'total_working_days': 37,
      'days_absent': 0,
      'days_present': 37,
      'attendance_percentage': 100.00,
      'department': 'Computer Science Engineering',
      'semester': 4,
    },
    {
      'serial_no': 56,
      'registration_no': '210823104058',
      'student_name': 'JESSICA M',
      'total_working_days': 37,
      'days_absent': 4,
      'days_present': 33,
      'attendance_percentage': 89.19,
      'department': 'Computer Science Engineering',
      'semester': 4,
    },
    {
      'serial_no': 57,
      'registration_no': '210823104059',
      'student_name': 'JOHN WESLY S (H)',
      'total_working_days': 37,
      'days_absent': 2,
      'days_present': 35,
      'attendance_percentage': 94.59,
      'department': 'Computer Science Engineering',
      'semester': 4,
    },
    {
      'serial_no': 58,
      'registration_no': '210823104060',
      'student_name': 'JOSELIN SARANISHA D (H)',
      'total_working_days': 37,
      'days_absent': 0,
      'days_present': 37,
      'attendance_percentage': 100.00,
      'department': 'Computer Science Engineering',
      'semester': 4,
    },
    {
      'serial_no': 59,
      'registration_no': '210823104061',
      'student_name': 'KARTHIKAISELVI P (H)',
      'total_working_days': 37,
      'days_absent': 0,
      'days_present': 37,
      'attendance_percentage': 100.00,
      'department': 'Computer Science Engineering',
      'semester': 4,
    },
    {
      'serial_no': 60,
      'registration_no': '210823104062',
      'student_name': 'KARTHIKEYAN D',
      'total_working_days': 37,
      'days_absent': 17,
      'days_present': 20,
      'attendance_percentage': 54.05,
      'department': 'Computer Science Engineering',
      'semester': 4,
    },
    {
      'serial_no': 61,
      'registration_no': '210823104063',
      'student_name': 'KARTHIKEYAN D',
      'total_working_days': 37,
      'days_absent': 13,
      'days_present': 24,
      'attendance_percentage': 64.86,
      'department': 'Computer Science Engineering',
      'semester': 4,
    },
  ];

  Future<Map<String, dynamic>?> getAttendanceByRegistrationNo(
    String registrationNo,
  ) async {
    try {
      // Clean up input - remove whitespace and # symbol if present
      final cleanedRegNo = registrationNo.trim().replaceAll('#', '');

      print('Searching for registration number: $cleanedRegNo');

      // Direct query with exact match from local data
      final exactMatch =
          _attendanceData
              .where((record) => record['registration_no'] == cleanedRegNo)
              .toList();

      if (exactMatch.isNotEmpty) {
        print('Found exact match for registration number: $cleanedRegNo');
        return exactMatch[0];
      }

      // No exact match found - try checking if this contains a valid registration number or name
      print('No exact match found. Trying alternative search...');

      // Try partial registration number match
      for (var record in _attendanceData) {
        if (record['registration_no'].toString().contains(cleanedRegNo) ||
            cleanedRegNo.contains(record['registration_no'].toString())) {
          print(
            'Found partial registration match: ${record['registration_no']}',
          );
          return record;
        }
      }

      // Then try name match (case insensitive)
      final lowerCaseInput = cleanedRegNo.toLowerCase();
      for (var record in _attendanceData) {
        final studentName = record['student_name'].toString().toLowerCase();
        if (studentName.contains(lowerCaseInput) ||
            lowerCaseInput.contains(studentName)) {
          print('Found student name match: ${record['student_name']}');
          return record;
        }
      }

      print('No record found with registration number: $cleanedRegNo');
      return null;
    } catch (error) {
      print('Error fetching attendance: $error');
      return null;
    }
  }

  // Get a list of all registration numbers for reference
  Future<List<Map<String, dynamic>>> getAllRegistrationNumbers() async {
    try {
      // Return registration numbers and names from local data
      return _attendanceData
          .map(
            (record) => {
              'registration_no': record['registration_no'],
              'student_name': record['student_name'],
            },
          )
          .toList();
    } catch (error) {
      print('Error fetching registration numbers: $error');
      return [];
    }
  }
}
